export { default as createUrl } from './createUrl';
export { default as generateSptintWord } from './generateSptintWord';
export { default as getData } from './getData';
export { default as getSeveralPageData } from './getSeveralPageData';
export { default as ejectByID } from './ejectById';
export { default as arrayShuffle } from './arrayShuffle';
export { default as getTranslaties } from './getTranslaties';
export { default as createAudio } from './createAudio';
export { default as getButtonType } from './getButtonType';
